services:
  app:
    build: .
    ports:
      - "3007:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_HOST=127.0.0.1
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=i@Passw0rd
      - DATABASE_NAME=gps
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - mosquitto
      - redis

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=i@Passw0rd
      - DATABASE_NAME=gps
      - PGTZ=Asia/Bangkok
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_config:/mosquitto/config
      - mosquitto_log:/mosquitto/log
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  redis:
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_config:
  mosquitto_log:
  redis_data: