import { Column, CreateDateColumn, DeleteDateColumn, Entity, Index, JoinColumn, ManyToOne, PrimaryGeneratedColumn, UpdateDateColumn } from "typeorm";

@Entity()
export class Gp {

    @PrimaryGeneratedColumn({ comment: 'The primary key identifier, auto-generated by the database.' })
    id: number;

    @CreateDateColumn({ name: "created_at", comment: 'The date and time when the record was created.' })
    createdAt!: Date;

    @UpdateDateColumn({ name: "updated_at", comment: 'The date and time when the record was last updated.' })
    updatedAt!: Date;

    @DeleteDateColumn({ name: "deleted_at", comment: 'The date and time when the record was soft deleted. This field is optional and will be null if not deleted.' })
    deletedAt?: Date;

    @Column({nullable: true,type: 'float'})
    lat: number;

    @Column({nullable: true,type: 'float'})
    long: number;

    @Column({nullable: true,type: 'float'})
    speed: number;

    @Column({ nullable: true, type: 'timestamptz' })
    gpstime: Date;

    
}
